dezswap/cosmwasm-etl

parser/dezswap/mappers.go, pkg/rules/dezswap/consts.go
=> Remove length check from wasmTransferMapper, Naming

aggregator/task.go
=> fix: update route repo to indicate dest one

pkg/terra/col4/dto.go, pkg/terra/col4/lcd.go, pkg/terra/col4/rpc.go, pkg/terra/fcd/fcd.go
- Terra columbus-4 network LCD, RPC Clients, FCD client for Terra network
=> Terra LCD, RPC, FCD clients

.gitignore, cmd/parser/main.go, configs/node.config.go, configs/parser.config.go, example.config.yaml, parser/srcstore/terraswap/col4_datastore.go, parser/srcstore/terraswap/col4_mappers.go, parser/terraswap/app.go, parser/terraswap/app_test.go, parser/terraswap/mappers.go, parser/terraswap/mappers_test.go, parser/utils.go, pkg/rules/terraswap/col4_logfinders.go, pkg/rules/terraswap/consts.go
- TerraSwap columbus-4 network parser
=> TerraSwap columbus-4 parser

configs/parser.config.go, example.config.yaml, parser/dex.go, parser/interfaces.go, parser/mocks.go, parser/repo/repository.go
- Validation logic for `parsed_tx` amount
=> Validation for `parsed_tx`

Makefile, db/migrations/collector/20240109170034_fcd_tx_log.down.sql, db/migrations/collector/20240109170034_fcd_tx_log.up.sql, db/migrations/collector/main.go, db/migrations/collector/template.txt, pkg/db/schemas/collector.models.go
- Reopen https://github.com/dezswap/cosmwasm-etl/pull/14
=> Migration for FCD collector

aggregator/task.go, pkg/db/parser/repository.go
=> fix: retrieve last price if not exist in a target range

go.mod, go.sum, parser/dex.go, parser/terraswap/app_test.go, parser/terraswap/mappers.go, parser/terraswap/mappers_test.go, parser/utils.go
=> Validation for previous synced height

db/migrations/aggregator/20240205191726_last_price.down.sql, db/migrations/aggregator/20240205191726_last_price.up.sql, pkg/db/parser/repository.go
=> fix: invert last_swap_price

collector/collector_test.go, collector/datastore/datastore.go, collector/datastore/datastore_test.go
- Major Reviewer: @psy2848048 
- pairs query need to be requested several times
- request until empty pair list
=> fix: bug fix for all pairs query

parser/dex/srcstore/datastore.go, parser/dex/srcstore/datastore_test.go, parser/dex/srcstore/mappers.go, parser/srcstore/datastore.go, parser/srcstore/datastore_test.go, parser/srcstore/mappers.go
=> Refactor: split common source store from parser.dex

parser/dex/terraswap/columbus_v1/mappers.go, parser/dex/terraswap/phoenix/mappers.go, parser/dex/terraswap/phoenix/mappers_test.go, pkg/dex/terraswap/phoenix/consts.go, pkg/terra/const.go, pkg/terra/utils.go
=> feat: refund asset for TerraSwap provide

.github/workflows/ci.yml, aggregator/task.go, pkg/db/parser/repository.go, pkg/dex/price/price.go
=> refactor: detailed log for num parsing

aggregator/task.go, pkg/dex/price/constants.go, pkg/dex/price/price.go, pkg/dex/price/repository.go
=> feat: set liquidity threshold in price calculation

pkg/db/parser/repository.go, pkg/util/decimals.go
=> fix: parse exponential format number

.github/workflows/cd.yml, .gitignore, Dockerfile, Makefile, cmd/parser/dex/main.go, cmd/parser/main.go, configs/parser.config.go, example.config.yaml, parser/dex/dex.go, parser/dex/dezswap/app.go, parser/dex/starfleit/app.go, parser/dex/terraswap/app_factory.go, parser/dex/terraswap/columbus_v1/app.go, parser/dex/terraswap/columbus_v1/app_test.go, parser/dex/terraswap/phoenix/app.go, parser/dex/terraswap/phoenix/app_test.go
:warning: This PR requires config file change, DO NOT MERGE until you modify the deployed config file
=> Add `dex` property to config 

parser/dex/dezswap/app.go, parser/dex/dezswap/mappers.go, parser/dex/dezswap/mappers_test.go, parser/dex/mapper.go, parser/dex/mappers_test.go, parser/dex/starfleit/app.go, parser/dex/starfleit/mappers.go, parser/dex/terraswap/columbusv2/app.go, parser/dex/terraswap/phoenix/app.go, pkg/dex/const.go, pkg/dex/dezswap/consts.go, pkg/dex/dezswap/logfinders.go, pkg/dex/dezswap/logfinders_test.go, pkg/dex/logfinder.go, pkg/dex/logfinders_test.go
=> Initial provide for TerraSwap

pkg/dex/price/price.go
=> fix: prevent price calculation with zero

aggregator/aggregator_test.go, aggregator/task.go, aggregator/task_test.go, pkg/db/parser/repository.go
=> fix: replace price into prev value when volume is zero

aggregator/task.go, pkg/db/parser/repository.go
=> fix: prevent omitting stats which price is not figured

.github/workflows/cd.yml
- Major Reviewer:
Correct `aws-region` value not defined as a environment variable to input value
=> fix: correct region for login

.github/workflows/cd.yml
=> fix: incorrect step id

.github/workflows/cd.yml
=> chore: update version for ecs deploy

.github/CODEOWNERS, .github/workflows/cd.yml
=> ci: add doraro as a network option
